name: circle_translate

# Controls when the workflow will run
on:
  # Triggers the workflow on a schedule (every day at 02:43 UTC)
  schedule:
    - cron: '0 */6 * * *'
   - cron: '37 21 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v4  # 更新到 v4
        with:
          token: ${{ secrets.WORK_TOKEN }}

      # Set up Python 3.8
      - name: Set up Python 3.8
        uses: actions/setup-python@v5  # 更新到 v5
        with:
          python-version: '3.8'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install beautifulsoup4 pygtrans feedparser rfeed

      # Run the main scripts
      - name: Run scripts and list files
        run: |
          python main2.py
          python .github/cron_random.py
          ls -al rss/
      - name: Upload RSS artifacts
        uses: actions/upload-artifact@v4
        with:
          name: rss-files
          path: rss/
          
      # Commit and push changes
      - name: Push changes
        env:
          U_NAME: ${{ secrets.U_NAME }}
          U_EMAIL: ${{ secrets.U_EMAIL }}
        run: |
          pwd
          git config --local user.name "${U_NAME}"
          git config --local user.email "${U_EMAIL}"
          
          git status -s
          git add rss/*
          git add test.ini
          git add .github/workflows/circle_translate.yml
          git add README.md
          
          export TZ='Asia/Shanghai'
          git commit -m "Github RSS Translate Auto Builder at `date +'%Y-%m-%d %H:%M'`"
          
          echo "======git push===="
          git push
